<?php
/**
 * Svea checkout Cart Summary Template
 *
 * @package Svea_Checkout
 * @module  Svea
 * @author  Webbhuset <info@webbhuset.se>
 * @see     Svea_Checkout_Block_Checkout_Cart
 */
?>
<form id="country-form">
    <?php
    $selectedCountry = $this->getQuote()->getShippingAddress()->getCountryId();
    $countryId = ($selectedCountry) ? $selectedCountry : null;
    echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($countryId)
    ?>
</form>
