<?php

/**
 * Template renderer for additional block
 *
 * @package Svea_Checkout
 * @module  Svea
 * @author  Webbhuset <info@webbhuset.se>
 * @see     Mage_Checkout_Block_Onepage_Shipping_Method_Additional
 */
?>
<?php if (!$this->getQuote()->isVirtual()): ?>
    <?= $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
<?php endif; ?>
