
<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="shipping-zip-form">
    <p class="shipping-desc"><?php echo $this->__('Enter your destination to get a shipping estimate.') ?></p>
    <ul class="form-list">
        <li class="shipping-country">
            <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
            <div class="input-box">
                <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>
            </div>
        </li>
        <?php // if($this->getStateActive()): ?>
        <li class="shipping-region">
            <?php /* Removing the conditional check for whether the region is required, because it doesn't work
                <label for="region_id"<?php if ($this->isStateProvinceRequired()) echo ' class="required"' ?>><?php if ($this->isStateProvinceRequired()) echo '<em>*</em>' ?><?php echo $this->__('State/Province') ?></label>
                */ ?>
            <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
            <div class="input-box">
                <select id="region_id" name="region_id" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" style="display:none;"<?php echo ($this->isStateProvinceRequired() ? ' class="validate-select"' : '') ?>>
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                  //<![CDATA[
                  $('region_id').setAttribute('defaultValue',  "<?php echo $this->getEstimateRegionId() ?>");
                  //]]>
                </script>
                <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getEstimateRegion()) ?>"  title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text" style="display:none;" />
            </div>
        </li>
        <?php // endif; ?>
        <?php if($this->getCityActive()): ?>
            <li class="shipping-region">
                <label for="city"<?php if ($this->isCityRequired()) echo ' class="required"' ?>><?php if ($this->isCityRequired()) echo '<em>*</em>' ?><?php echo $this->__('City') ?></label>
                <div class="input-box">
                    <input class="input-text<?php if ($this->isCityRequired()):?> required-entry<?php endif;?>" id="city" type="text" name="estimate_city" value="<?php echo $this->escapeHtml($this->getEstimateCity()) ?>" />
                </div>
            </li>
        <?php endif; ?>
        <li class="shipping-postcode">
            <?php /* Removing the conditional check for whether the postal code is required, because it doesn't work
                <label for="postcode"<?php if ($this->isZipCodeRequired()) echo ' class="required"' ?>><?php if ($this->isZipCodeRequired()) echo '<em>*</em>' ?><?php echo $this->__('Zip/Postal Code') ?></label>
                */ ?>
            <label for="postcode" class="required"><em>*</em><?php echo $this->__('Zip') ?></label>
            <div class="input-box">
                <input class="input-text validate-postcode<?php if ($this->isZipCodeRequired()):?> required-entry<?php endif;?>" type="text" id="postcode" name="estimate_postcode" value="<?php echo $this->escapeHtml($this->getEstimatePostcode()) ?>" />
            </div>
        </li>
    </ul>
    <div class="buttons-set">
        <button type="button" title="<?php echo $this->quoteEscape($this->__('Estimate')) ?>" onclick="coShippingMethodForm.submit()" class="button2">
            <span><span><?php echo $this->__('Estimate') ?></span></span>
        </button>
    </div>
</form>
<script type="text/javascript">
  //<![CDATA[
  new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
  //]]>
</script>