<?php

/**
 * Template renderer for all available shipping methods and rates
 *
 * @package Svea_Checkout
 * @module  Svea
 * @author  Webbhuset <info@webbhuset.se>
 * @see     Svea_Checkout_Block_Checkout_Shipping_Methods
 */
?>
<?= $this->getChildHtml('checkout.onepage.combability') ?>
<form id="co-shipping-method-form" action="/checkout/cart/estimateUpdatePost/">
    <?php if ($this->isShippingMethodsHidden()): ?>
        <input type="hidden" name="shipping_method" value="<?= $this->getDefaultShippingMethod() ?>">
    <?php else: ?>
        <div class="checkout-block">
            <h2>
                <?= $this->__('Shipping and handling') ?>
            </h2>
            <div>
                <?= $this->getChildHtml('cart_shipping') ?>

                <div id="checkout-shipping-method-load">
                    <?= $this->getChildHtml('checkout.shipping.available') ?>
                </div>
                <div id="onepage-checkout-shipping-method-additional-load">
                    <?= $this->getChildHtml('checkout.shipping.additional') ?>
                </div>
            </div>
        </div>
    <?php endif ?>
</form>